config/routes.rb
BugTrackingSystem::Application.routes.draw do
  

  devise_for :users
netzke
   match '/index',    to: 'welcome#index'

  root to: 'static_pages#home'
 
  match '/help',    to: 'static_pages#help'
  match '/about',   to: 'static_pages#about'
  match '/contact', to: 'static_pages#contact'

end

app/models/task.rb
class Task < ActiveRecord::Base
  attr_accessible :done, :due, :name, :bug, :notes, :priority 
  validates :name, presence: true
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me
  # attr_accessible :title, :body
  
  
  include Gravtastic
  gravtastic :secure => true,
              
              :size => 120
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
  end
  
def create
  @user = User.create( params[:user] )
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController

  def home
  end

  def help
  end

  def about
  end
  
  def contact
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
def gravatar_for(user)
    gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
    gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}"
    image_tag(gravatar_url, alt: user.email, class: "gravatar")
    end
  # Returns the full title on a per-page basis.
  def full_title(page_title)
    base_title = "Bug Tracking System"
    if page_title.empty?
      base_title
    else
      "#{base_title} | #{page_title}"
    end
  end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/_footer.html.erb
<footer class="footer">
  <small>
    <a href="http://uk.wikipedia.org/wiki/%D0%91%D0%B0%D0%B3%D1%82%D1%80%D0%B5%D0%BA%D0%B5%D1%80">Багтрекер</a>
    від Бойка Олексія
  </small>
  <nav>
    <ul>
      <li><%= link_to "Про нас",   about_path %></li>
      <li><%= link_to "Контакти", contact_path %></li>
      <li><a href="http://lmgtfy.com/?q=%D0%9D%D0%BE%D0%B2%D0%B8%D0%BD%D0%B8+%D0%B7+%D1%81%D0%B2%D1%96%D1%82%D1%83+%D0%91%D0%B0%D0%B3%D1%82%D1%80%D0%B5%D0%BA%D1%96%D0%BD%D0%B3%D1%83">Новини</a></li>
    </ul>
  </nav>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="navbar-inner">
     <div id="user_nav">
    <div class="container">
      <%= link_to "Багтрекер", root_path, id: "logo" %>
      <nav>
        <ul class="nav pull-right">
          <li><%= link_to "Домашня сторінка",    root_path %></li>
          <li><%= link_to "Допомога",    help_path %></li>   
 <li> <% if user_signed_in? %></li>
    <li><%= link_to "ToDo List",    index_path %></li> 
   
 <li>  <%= link_to "Вийти", destroy_user_session_path, :method => :delete %>
  <% else %>
   <li>  <%= link_to "Зареєструватися", new_user_registration_path %> 
   <li>  <%= link_to "Увійти", new_user_session_path %>
  <% end %>
</li>
        </ul>
      </nav>
    </div>
  </div>
</header>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
<script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
   <%= render 'layouts/shim' %>
<%= load_netzke %>

    <title><%= full_title(yield(:title)) %></title>
    <%= stylesheet_link_tag    "application", media: "all" %>
    <%= javascript_include_tag "application" %>
    <%= csrf_meta_tags %>
  <%= csrf_meta_tag %>
  </head>
  <body>
    <%= render 'layouts/header' %>
    <div class="container">
      <%= yield %>
      <%= render 'layouts/footer' %>
    </div>
  </body>
</html>

app/views/static_pages/about.html.erb
<% provide(:title, 'Про нас') %>
<h1>Про нас</h1>
<p>
   <a href="http://localhost:3000/">Система Багтрекінгу</a> - 
   проект, розроблений, щоб допомогти тестерам та програмістам відстежувати роботу з багами під час своєї роботи. Він може розглядатись як різновид issue tracking system. 
  <p> Детальніше про сичтему Багтрекінгу можите <a href="http://uk.wikipedia.org/wiki/%D0%91%D0%B0%D0%B3%D1%82%D1%80%D0%B5%D0%BA%D0%B5%D1%80"> ознайомитися тут</a> .
  </p>

app/views/static_pages/contact.html.erb
<% provide(:title, 'Контакти') %>
<h1>Контакти</h1>
<p>
 Якщо ви маєте якісь запитання/пропозиції зв'яжіться з нами
  <a href="http://ua.linkedin.com/pub/olexey-boyko/69/395/8b5/">з нами</a>.
</p>

app/views/static_pages/help.html.erb
<% provide(:title, 'Допомога') %>
<h1>Допомога</h1>
<p>
 Щоб отримати допомогу про роботу системи Багтрекінгу. Та отримати будь-яку інформацію,яка вам не зрозуміла, використовуйте  
  <a href="http://google.ru/">пошук</a>.
  </a>
</p>

app/views/static_pages/home.html.erb
<div class="center hero-unit">
  <h1>Вітаємо вас в Системі Керування Проектами!</h1>

  <h2>
    Це головна сторінка для 
    <a href="http://localhost:3000/">Системи керування Проектами</a>
    .
  </h2>



   <%= link_to "Зареєструватися", new_user_registration_path , class: "btn btn-large btn-primary" %>
</div>


<%= link_to image_tag("bug.png", alt: "Rails"), 'http://uk.wikipedia.org/wiki/%D0%91%D0%B0%D0%B3%D1%82%D1%80%D0%B5%D0%BA%D0%B5%D1%80' %>  
 
 
  
<li> <% if user_signed_in? %></li>
 <li>  <%= link_to "Edit", edit_user_registration_path %> 
<% end %>





<sh>Поділитись з друзями:</sh>
<icons>
<script type="text/javascript" src="//yandex.st/share/share.js"
charset="utf-8"></script>
<div class="yashare-auto-init" data-yashareL10n="ru"
 data-yashareType="none" data-yashareQuickServices="yaru,vkontakte,facebook,twitter,odnoklassniki,moimir"
>

</div>
</icons>

app/views/welcome/index.html.erb
<h1>Tasks</h1>
<%= netzke :task_tab_panel, height: 400 %>